[project]
name = "genai-pracice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.108",
    "botocore[crt]>=1.43.108",
    "langchain>=1.4.3",
]

[project.scripts]
genai-pracice = "genai_pracice:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
